"""add source message to document artifacts

Revision ID: 047f9129a493
Revises: c7144259ca5f
Create Date: 2026-08-12 16:24:08.324312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '047f9129a493'
down_revision: Union[str, Sequence[str], None] = 'c7144259ca5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_artifacts', sa.Column('source_message_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('uq_document_artifact_document_summary'), table_name='document_artifacts', postgresql_where='(conversation_id IS NULL)')
    op.create_index(op.f('ix_document_artifacts_source_message_id'), 'document_artifacts', ['source_message_id'], unique=False)
    op.create_foreign_key(None, 'document_artifacts', 'messages', ['source_message_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'document_artifacts', type_='foreignkey')
    op.drop_index(op.f('ix_document_artifacts_source_message_id'), table_name='document_artifacts')
    op.create_index(op.f('uq_document_artifact_document_summary'), 'document_artifacts', ['document_id', 'type'], unique=True, postgresql_where='(conversation_id IS NULL)')
    op.drop_column('document_artifacts', 'source_message_id')
    # ### end Alembic commands ###
