"""update tables

Revision ID: 0c6052c4e847
Revises: fd68228867ca
Create Date: 2026-08-03 01:52:25.955769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c6052c4e847'
down_revision: Union[str, Sequence[str], None] = 'fd68228867ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_document_workspace_filename', 'documents', ['workspace_id', 'original_filename'])
    op.add_column('messages', sa.Column('document_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_messages_document_id'), 'messages', ['document_id'], unique=False)
    op.create_foreign_key("fk_messages_document_id", 'messages', 'documents', ['document_id'], ['id'], ondelete='SET NULL')
    op.create_unique_constraint('uq_workspace_user_title', 'workspaces', ['user_id', 'title'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_workspace_user_title', 'workspaces', type_='unique')
    op.drop_constraint("fk_messages_document_id", 'messages', type_='foreignkey')
    op.drop_index(op.f('ix_messages_document_id'), table_name='messages')
    op.drop_column('messages', 'document_id')
    op.drop_constraint('uq_document_workspace_filename', 'documents', type_='unique')
    # ### end Alembic commands ###
