"""add document chunks, updated

Revision ID: 15a2958204dd
Revises: 60c4a8290134
Create Date: 2026-08-18 19:25:42.288018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15a2958204dd'
down_revision: Union[str, Sequence[str], None] = '60c4a8290134'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('source_start', sa.Integer(), nullable=True))
    op.add_column('document_chunks', sa.Column('source_end', sa.Integer(), nullable=True))
    op.drop_column('document_chunks', 'page_end')
    op.drop_column('document_chunks', 'page_start')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('page_start', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('document_chunks', sa.Column('page_end', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('document_chunks', 'source_end')
    op.drop_column('document_chunks', 'source_start')
    # ### end Alembic commands ###
