"""add question attempts to document artifacts

Revision ID: 15bc19dc9db0
Revises: 9a0424d63f07
Create Date: 2026-08-12 06:17:26.524846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '15bc19dc9db0'
down_revision: Union[str, Sequence[str], None] = '9a0424d63f07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_artifacts', sa.Column('question_attempts', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_artifacts', 'question_attempts')
    # ### end Alembic commands ###
