"""migrated to conversation architecture

Revision ID: 2e978f410f5f
Revises: 76179b0bef0e
Create Date: 2026-08-06 04:59:10.472643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e978f410f5f'
down_revision: Union[str, Sequence[str], None] = '76179b0bef0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('conversation_type', sa.Enum('workspace', 'document', name='conversation_type'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'document_id', name='uq_workspace_document_conversation')
    )
    op.create_index(op.f('ix_conversations_document_id'), 'conversations', ['document_id'], unique=False)
    op.create_index(op.f('ix_conversations_workspace_id'), 'conversations', ['workspace_id'], unique=False)
    op.add_column('messages', sa.Column('conversation_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_messages_document_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_workspace_id'), table_name='messages')
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.drop_constraint(op.f('messages_workspace_id_fkey'), 'messages', type_='foreignkey')
    op.drop_constraint(op.f('fk_messages_document_id'), 'messages', type_='foreignkey')
    op.create_foreign_key('fk_messages_conversation_id', 'messages', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.drop_column('messages', 'workspace_id')
    op.drop_column('messages', 'document_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('document_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('workspace_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint('fk_messages_conversation_id', 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('fk_messages_document_id'), 'messages', 'documents', ['document_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('messages_workspace_id_fkey'), 'messages', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.create_index(op.f('ix_messages_workspace_id'), 'messages', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_messages_document_id'), 'messages', ['document_id'], unique=False)
    op.drop_column('messages', 'conversation_id')
    op.drop_index(op.f('ix_conversations_workspace_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_document_id'), table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
