"""remove document status

Revision ID: 3af0fdb9d242
Revises: 093300343a23
Create Date: 2026-07-30 01:43:43.268423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3af0fdb9d242'
down_revision: Union[str, Sequence[str], None] = '093300343a23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('status', postgresql.ENUM('UPLOADED', 'PROCESSING', 'COMPLETED', 'FAILED', name='documentstatus'), server_default=sa.text("'UPLOADED'::documentstatus"), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
