"""update Document model

Revision ID: 425b0c8e56f4
Revises: 4e4bf6c574fa
Create Date: 2026-07-28 03:34:59.311871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '425b0c8e56f4'
down_revision: Union[str, Sequence[str], None] = '4e4bf6c574fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('upload_directory', sa.String(length=1000), nullable=False))
    op.alter_column('documents', 'storage_path',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000),
               existing_nullable=False)
    op.drop_constraint(op.f('documents_stored_filename_key'), 'documents', type_='unique')
    op.drop_column('documents', 'stored_filename')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('stored_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('documents_stored_filename_key'), 'documents', ['stored_filename'], postgresql_nulls_not_distinct=False)
    op.alter_column('documents', 'storage_path',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    op.drop_column('documents', 'upload_directory')
    # ### end Alembic commands ###
