"""added active field for document

Revision ID: 8ee04308796f
Revises: 2e978f410f5f
Create Date: 2026-08-07 07:17:22.381715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ee04308796f'
down_revision: Union[str, Sequence[str], None] = '2e978f410f5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('include_in_workspace_context', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('documents', 'include_in_workspace_context')
    # ### end Alembic commands ###
