"""added progrees to document

Revision ID: 9915990cf7c7
Revises: f024acbc8ebd
Create Date: 2026-08-22 12:36:17.532198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9915990cf7c7'
down_revision: Union[str, Sequence[str], None] = 'f024acbc8ebd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('stage', sa.String(length=50), nullable=True))
    op.add_column('documents', sa.Column('progress', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'progress')
    op.drop_column('documents', 'stage')
    # ### end Alembic commands ###
