"""add conversation scope to document artifacts

Revision ID: c7144259ca5f
Revises: 15bc19dc9db0
Create Date: 2026-08-12 07:27:36.690929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7144259ca5f'
down_revision: Union[str, Sequence[str], None] = '15bc19dc9db0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_artifacts', sa.Column('conversation_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('uq_document_artifact_type'), 'document_artifacts', type_='unique')
    op.create_index(op.f('ix_document_artifacts_conversation_id'), 'document_artifacts', ['conversation_id'], unique=False)
    op.create_foreign_key(None, 'document_artifacts', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.create_index( "uq_document_artifact_document_summary", "document_artifacts", ["document_id", "type"], unique=True, postgresql_where=sa.text("conversation_id IS NULL"), )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index(
        "uq_document_artifact_document_summary",
        table_name="document_artifacts",
    )

    op.drop_constraint(
        None,
        "document_artifacts",
        type_="foreignkey",
    )

    op.drop_index(
        op.f("ix_document_artifacts_conversation_id"),
        table_name="document_artifacts",
    )

    op.create_unique_constraint(
        op.f("uq_document_artifact_type"),
        "document_artifacts",
        ["document_id", "type"],
        postgresql_nulls_not_distinct=False,
    )

    op.drop_column("document_artifacts", "conversation_id")
