"""add document processing status

Revision ID: f024acbc8ebd
Revises: 15a2958204dd
Create Date: 2026-08-20 22:51:44.733474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f024acbc8ebd'
down_revision: Union[str, Sequence[str], None] = '15a2958204dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(
        op.f("ix_document_contents_document_id"),
        table_name="document_contents",
    )

    op.drop_table("document_contents")

    document_status = sa.Enum(
        "PROCESSING",
        "READY",
        "FAILED",
        name="document_status",
    )

    document_status.create(op.get_bind(), checkfirst=True)

    op.add_column(
        "documents",
        sa.Column(
            "status",
            document_status,
            server_default="PROCESSING",
            nullable=False,
        ),
    )

    op.add_column(
        "documents",
        sa.Column(
            "processing_error",
            sa.String(length=1000),
            nullable=True,
        ),
    )

    op.execute(
        """
        UPDATE documents
        SET status = 'READY'
        """
    )

    op.drop_index(
        op.f("uq_workspace_user_default"),
        table_name="workspaces",
        postgresql_where="(is_default = true)",
    )

    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###

    op.create_index(
        op.f("uq_workspace_user_default"),
        "workspaces",
        ["user_id"],
        unique=True,
        postgresql_where="(is_default = true)",
    )

    op.drop_column("documents", "processing_error")
    op.drop_column("documents", "status")

    op.execute("DROP TYPE IF EXISTS document_status")

    op.create_table(
        "document_contents",
        sa.Column(
            "id",
            sa.INTEGER(),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "document_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "content",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("document_contents_document_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name=op.f("document_contents_pkey"),
        ),
    )

    op.create_index(
        op.f("ix_document_contents_document_id"),
        "document_contents",
        ["document_id"],
        unique=True,
    )

    # ### end Alembic commands ###