CHAT_TEMPERATURE = 0.7
CHAT_MAX_OUTPUT_TOKENS = 1000

SUMMARY_TEMPERATURE = 0.3
SUMMARY_MAX_OUTPUT_TOKENS = 2000

SUMMARY_CONTEXT_WINDOW = 65_000
SUMMARY_TPM_LIMIT = 30_000

SUMMARY_INPUT_TOKEN_BUDGET = min(
    SUMMARY_CONTEXT_WINDOW - SUMMARY_MAX_OUTPUT_TOKENS,
    SUMMARY_TPM_LIMIT - SUMMARY_MAX_OUTPUT_TOKENS,
)

SUMMARY_REDUCTION_INPUT_TOKEN_BUDGET = min(
    SUMMARY_CONTEXT_WINDOW - SUMMARY_MAX_OUTPUT_TOKENS,
    SUMMARY_TPM_LIMIT - SUMMARY_MAX_OUTPUT_TOKENS,
)

SUMMARY_PARTIAL_MAX_OUTPUT_TOKENS = 1_200
SUMMARY_INTERMEDIATE_MAX_OUTPUT_TOKENS = 1_200
SUMMARY_FINAL_MAX_OUTPUT_TOKENS = 1_200

TOPIC_CONSOLIDATION_INPUT_TOKEN_BUDGET = 4000

CONVERSATION_SUMMARY_INPUT_TOKEN_BUDGET = 6000
CONVERSATION_SUMMARY_REDUCTION_INPUT_TOKEN_BUDGET = 6000

QUIZ_TEMPERATURE = 0.9
QUIZ_MAX_OUTPUT_TOKENS = 1200

FLASHCARD_TEMPERATURE = 0.4
FLASHCARD_MAX_OUTPUT_TOKENS = 1000